# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.records__post_api import RecordsPostApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRecordsPostApi(unittest.TestCase):
    """RecordsPostApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.records__post_api.RecordsPostApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_records_post(self):
        """Test case for records_post

        Creates new records or updates existing records with the given record buffer times.  # noqa: E501
        """
        pass

    def test_records_post_0(self):
        """Test case for records_post_0

        Creates a new record or updates an existing record with the given record buffer times.  # noqa: E501
        """
        pass

    def test_records_post_resume(self):
        """Test case for records_post_resume

        Stores the current stream position for later resume.  # noqa: E501
        """
        pass

    def test_records_post_tag_download_completed(self):
        """Test case for records_post_tag_download_completed

        Creates a tag to mark the record as downloaded.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
