# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.save_tv_web_api_request_models_playlist_id_list import SaveTVWebApiRequestModelsPlaylistIdList  # noqa: E501
from swagger_client.rest import ApiException


class TestSaveTVWebApiRequestModelsPlaylistIdList(unittest.TestCase):
    """SaveTVWebApiRequestModelsPlaylistIdList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSaveTVWebApiRequestModelsPlaylistIdList(self):
        """Test SaveTVWebApiRequestModelsPlaylistIdList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.save_tv_web_api_request_models_playlist_id_list.SaveTVWebApiRequestModelsPlaylistIdList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
