# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.stars__get_api import StarsGetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStarsGetApi(unittest.TestCase):
    """StarsGetApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.stars__get_api.StarsGetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_stars_get(self):
        """Test case for stars_get

        Retrieves the stars that match the filter condition.  # noqa: E501
        """
        pass

    def test_stars_get_0(self):
        """Test case for stars_get_0

        Retrieves a single star with the given identifier.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
