# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.records__get_api import RecordsGetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRecordsGetApi(unittest.TestCase):
    """RecordsGetApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.records__get_api.RecordsGetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_records_count(self):
        """Test case for records_count

        Retrieves the number of records for the current account that match the filter condition.  # noqa: E501
        """
        pass

    def test_records_download(self):
        """Test case for records_download

        Requests the download URL for a record.  # noqa: E501
        """
        pass

    def test_records_get(self):
        """Test case for records_get

        Retrieves the record for the current account that match the filter condition.  # noqa: E501
        """
        pass

    def test_records_get_0(self):
        """Test case for records_get_0

        Retrieves a single record with the given identifier.  # noqa: E501
        """
        pass

    def test_records_get_suggestions(self):
        """Test case for records_get_suggestions

        Provides suggestions for the telecast search text.  # noqa: E501
        """
        pass

    def test_records_groups(self):
        """Test case for records_groups

        Groups the records of the current user by the given key.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
