# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.olymp_web_api_response_models_error import OlympWebApiResponseModelsError  # noqa: E501
from swagger_client.rest import ApiException


class TestOlympWebApiResponseModelsError(unittest.TestCase):
    """OlympWebApiResponseModelsError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOlympWebApiResponseModelsError(self):
        """Test OlympWebApiResponseModelsError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.olymp_web_api_response_models_error.OlympWebApiResponseModelsError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
