# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tv_station_groups__get_api import TvStationGroupsGetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTvStationGroupsGetApi(unittest.TestCase):
    """TvStationGroupsGetApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.tv_station_groups__get_api.TvStationGroupsGetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tv_station_groups_get(self):
        """Test case for tv_station_groups_get

        Retrieves all available TV stations groups.  # noqa: E501
        """
        pass

    def test_tv_station_groups_get_0(self):
        """Test case for tv_station_groups_get_0

        Retrieves a single TV station group with the given identifier.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
