# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.save_tv_web_api_request_models_channel_telecast_fields_filter import SaveTVWebApiRequestModelsChannelTelecastFieldsFilter  # noqa: E501
from swagger_client.rest import ApiException


class TestSaveTVWebApiRequestModelsChannelTelecastFieldsFilter(unittest.TestCase):
    """SaveTVWebApiRequestModelsChannelTelecastFieldsFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSaveTVWebApiRequestModelsChannelTelecastFieldsFilter(self):
        """Test SaveTVWebApiRequestModelsChannelTelecastFieldsFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.save_tv_web_api_request_models_channel_telecast_fields_filter.SaveTVWebApiRequestModelsChannelTelecastFieldsFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
