# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.time_blocks__get_api import TimeBlocksGetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTimeBlocksGetApi(unittest.TestCase):
    """TimeBlocksGetApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.time_blocks__get_api.TimeBlocksGetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_time_blocks_get(self):
        """Test case for time_blocks_get

        Retrieves all EPG time blocks.  # noqa: E501
        """
        pass

    def test_time_blocks_get_0(self):
        """Test case for time_blocks_get_0

        Retrieves a single time block with the given identifier.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
