# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user__get_api import UserGetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserGetApi(unittest.TestCase):
    """UserGetApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.user__get_api.UserGetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_access_code_validate_access_code(self):
        """Test case for user_access_code_validate_access_code

        Validates the AccessCode  # noqa: E501
        """
        pass

    def test_user_get(self):
        """Test case for user_get

        Endpoint for getting the data of the requesting user.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
