# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.save_tv_web_api_request_models_star_filter import SaveTVWebApiRequestModelsStarFilter  # noqa: E501
from swagger_client.rest import ApiException


class TestSaveTVWebApiRequestModelsStarFilter(unittest.TestCase):
    """SaveTVWebApiRequestModelsStarFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSaveTVWebApiRequestModelsStarFilter(self):
        """Test SaveTVWebApiRequestModelsStarFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.save_tv_web_api_request_models_star_filter.SaveTVWebApiRequestModelsStarFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
