# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.save_tv_web_api_request_models_star_notification_delete_request import SaveTVWebApiRequestModelsStarNotificationDeleteRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestSaveTVWebApiRequestModelsStarNotificationDeleteRequest(unittest.TestCase):
    """SaveTVWebApiRequestModelsStarNotificationDeleteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSaveTVWebApiRequestModelsStarNotificationDeleteRequest(self):
        """Test SaveTVWebApiRequestModelsStarNotificationDeleteRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.save_tv_web_api_request_models_star_notification_delete_request.SaveTVWebApiRequestModelsStarNotificationDeleteRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
