# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.save_tv_erotic_videos_i_video_download_service import SaveTVEroticVideosIVideoDownloadService  # noqa: E501
from swagger_client.rest import ApiException


class TestSaveTVEroticVideosIVideoDownloadService(unittest.TestCase):
    """SaveTVEroticVideosIVideoDownloadService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSaveTVEroticVideosIVideoDownloadService(self):
        """Test SaveTVEroticVideosIVideoDownloadService"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.save_tv_erotic_videos_i_video_download_service.SaveTVEroticVideosIVideoDownloadService()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
