# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.save_tv_web_api_response_models_suggestion import SaveTVWebApiResponseModelsSuggestion  # noqa: E501
from swagger_client.rest import ApiException


class TestSaveTVWebApiResponseModelsSuggestion(unittest.TestCase):
    """SaveTVWebApiResponseModelsSuggestion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSaveTVWebApiResponseModelsSuggestion(self):
        """Test SaveTVWebApiResponseModelsSuggestion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.save_tv_web_api_response_models_suggestion.SaveTVWebApiResponseModelsSuggestion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
