# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.save_tv_video_on_demand_folx_tv_videos_i_domain_video_list_cache import SaveTVVideoOnDemandFolxTvVideosIDomainVideoListCache  # noqa: E501
from swagger_client.rest import ApiException


class TestSaveTVVideoOnDemandFolxTvVideosIDomainVideoListCache(unittest.TestCase):
    """SaveTVVideoOnDemandFolxTvVideosIDomainVideoListCache unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSaveTVVideoOnDemandFolxTvVideosIDomainVideoListCache(self):
        """Test SaveTVVideoOnDemandFolxTvVideosIDomainVideoListCache"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.save_tv_video_on_demand_folx_tv_videos_i_domain_video_list_cache.SaveTVVideoOnDemandFolxTvVideosIDomainVideoListCache()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
