# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.olymp_net45_audit_i_audit_info_provider import OlympNet45AuditIAuditInfoProvider  # noqa: E501
from swagger_client.rest import ApiException


class TestOlympNet45AuditIAuditInfoProvider(unittest.TestCase):
    """OlympNet45AuditIAuditInfoProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOlympNet45AuditIAuditInfoProvider(self):
        """Test OlympNet45AuditIAuditInfoProvider"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.olymp_net45_audit_i_audit_info_provider.OlympNet45AuditIAuditInfoProvider()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
