# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.erotic_videos__get_api import EroticVideosGetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEroticVideosGetApi(unittest.TestCase):
    """EroticVideosGetApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.erotic_videos__get_api.EroticVideosGetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_erotic_videos_download(self):
        """Test case for erotic_videos_download

        Requests the download URL for a record.  # noqa: E501
        """
        pass

    def test_erotic_videos_get(self):
        """Test case for erotic_videos_get

        Retrieves all erotic videos.  # noqa: E501
        """
        pass

    def test_erotic_videos_get_0(self):
        """Test case for erotic_videos_get_0

        Retrieves one erotic video.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
