# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class MicrosoftWin32SafeHandlesSafeWaitHandle(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_invalid': 'bool',
        'is_closed': 'bool'
    }

    attribute_map = {
        'is_invalid': 'IsInvalid',
        'is_closed': 'IsClosed'
    }

    def __init__(self, is_invalid=None, is_closed=None):  # noqa: E501
        """MicrosoftWin32SafeHandlesSafeWaitHandle - a model defined in Swagger"""  # noqa: E501

        self._is_invalid = None
        self._is_closed = None
        self.discriminator = None

        if is_invalid is not None:
            self.is_invalid = is_invalid
        if is_closed is not None:
            self.is_closed = is_closed

    @property
    def is_invalid(self):
        """Gets the is_invalid of this MicrosoftWin32SafeHandlesSafeWaitHandle.  # noqa: E501


        :return: The is_invalid of this MicrosoftWin32SafeHandlesSafeWaitHandle.  # noqa: E501
        :rtype: bool
        """
        return self._is_invalid

    @is_invalid.setter
    def is_invalid(self, is_invalid):
        """Sets the is_invalid of this MicrosoftWin32SafeHandlesSafeWaitHandle.


        :param is_invalid: The is_invalid of this MicrosoftWin32SafeHandlesSafeWaitHandle.  # noqa: E501
        :type: bool
        """

        self._is_invalid = is_invalid

    @property
    def is_closed(self):
        """Gets the is_closed of this MicrosoftWin32SafeHandlesSafeWaitHandle.  # noqa: E501


        :return: The is_closed of this MicrosoftWin32SafeHandlesSafeWaitHandle.  # noqa: E501
        :rtype: bool
        """
        return self._is_closed

    @is_closed.setter
    def is_closed(self, is_closed):
        """Sets the is_closed of this MicrosoftWin32SafeHandlesSafeWaitHandle.


        :param is_closed: The is_closed of this MicrosoftWin32SafeHandlesSafeWaitHandle.  # noqa: E501
        :type: bool
        """

        self._is_closed = is_closed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MicrosoftWin32SafeHandlesSafeWaitHandle, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MicrosoftWin32SafeHandlesSafeWaitHandle):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
