# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SaveTVWebApiResponseModelsDownload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'download_url': 'str',
        'streaming_url': 'str',
        'html_video_player_url': 'str',
        'file_name': 'str',
        'estimated_file_size': 'int',
        'resume_position': 'int'
    }

    attribute_map = {
        'download_url': 'downloadUrl',
        'streaming_url': 'streamingUrl',
        'html_video_player_url': 'htmlVideoPlayerUrl',
        'file_name': 'fileName',
        'estimated_file_size': 'estimatedFileSize',
        'resume_position': 'resumePosition'
    }

    def __init__(self, download_url=None, streaming_url=None, html_video_player_url=None, file_name=None, estimated_file_size=None, resume_position=None):  # noqa: E501
        """SaveTVWebApiResponseModelsDownload - a model defined in Swagger"""  # noqa: E501

        self._download_url = None
        self._streaming_url = None
        self._html_video_player_url = None
        self._file_name = None
        self._estimated_file_size = None
        self._resume_position = None
        self.discriminator = None

        if download_url is not None:
            self.download_url = download_url
        if streaming_url is not None:
            self.streaming_url = streaming_url
        if html_video_player_url is not None:
            self.html_video_player_url = html_video_player_url
        if file_name is not None:
            self.file_name = file_name
        if estimated_file_size is not None:
            self.estimated_file_size = estimated_file_size
        if resume_position is not None:
            self.resume_position = resume_position

    @property
    def download_url(self):
        """Gets the download_url of this SaveTVWebApiResponseModelsDownload.  # noqa: E501


        :return: The download_url of this SaveTVWebApiResponseModelsDownload.  # noqa: E501
        :rtype: str
        """
        return self._download_url

    @download_url.setter
    def download_url(self, download_url):
        """Sets the download_url of this SaveTVWebApiResponseModelsDownload.


        :param download_url: The download_url of this SaveTVWebApiResponseModelsDownload.  # noqa: E501
        :type: str
        """

        self._download_url = download_url

    @property
    def streaming_url(self):
        """Gets the streaming_url of this SaveTVWebApiResponseModelsDownload.  # noqa: E501


        :return: The streaming_url of this SaveTVWebApiResponseModelsDownload.  # noqa: E501
        :rtype: str
        """
        return self._streaming_url

    @streaming_url.setter
    def streaming_url(self, streaming_url):
        """Sets the streaming_url of this SaveTVWebApiResponseModelsDownload.


        :param streaming_url: The streaming_url of this SaveTVWebApiResponseModelsDownload.  # noqa: E501
        :type: str
        """

        self._streaming_url = streaming_url

    @property
    def html_video_player_url(self):
        """Gets the html_video_player_url of this SaveTVWebApiResponseModelsDownload.  # noqa: E501


        :return: The html_video_player_url of this SaveTVWebApiResponseModelsDownload.  # noqa: E501
        :rtype: str
        """
        return self._html_video_player_url

    @html_video_player_url.setter
    def html_video_player_url(self, html_video_player_url):
        """Sets the html_video_player_url of this SaveTVWebApiResponseModelsDownload.


        :param html_video_player_url: The html_video_player_url of this SaveTVWebApiResponseModelsDownload.  # noqa: E501
        :type: str
        """

        self._html_video_player_url = html_video_player_url

    @property
    def file_name(self):
        """Gets the file_name of this SaveTVWebApiResponseModelsDownload.  # noqa: E501


        :return: The file_name of this SaveTVWebApiResponseModelsDownload.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this SaveTVWebApiResponseModelsDownload.


        :param file_name: The file_name of this SaveTVWebApiResponseModelsDownload.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    @property
    def estimated_file_size(self):
        """Gets the estimated_file_size of this SaveTVWebApiResponseModelsDownload.  # noqa: E501


        :return: The estimated_file_size of this SaveTVWebApiResponseModelsDownload.  # noqa: E501
        :rtype: int
        """
        return self._estimated_file_size

    @estimated_file_size.setter
    def estimated_file_size(self, estimated_file_size):
        """Sets the estimated_file_size of this SaveTVWebApiResponseModelsDownload.


        :param estimated_file_size: The estimated_file_size of this SaveTVWebApiResponseModelsDownload.  # noqa: E501
        :type: int
        """

        self._estimated_file_size = estimated_file_size

    @property
    def resume_position(self):
        """Gets the resume_position of this SaveTVWebApiResponseModelsDownload.  # noqa: E501


        :return: The resume_position of this SaveTVWebApiResponseModelsDownload.  # noqa: E501
        :rtype: int
        """
        return self._resume_position

    @resume_position.setter
    def resume_position(self, resume_position):
        """Sets the resume_position of this SaveTVWebApiResponseModelsDownload.


        :param resume_position: The resume_position of this SaveTVWebApiResponseModelsDownload.  # noqa: E501
        :type: int
        """

        self._resume_position = resume_position

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SaveTVWebApiResponseModelsDownload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SaveTVWebApiResponseModelsDownload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
