# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SaveTVWebApiResponseModelsRecordGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'str',
        'title': 'str',
        'count': 'int',
        'records': 'list[SaveTVWebApiResponseModelsRecord]',
        'image_url100': 'str',
        'image_url250': 'str',
        'image_url500': 'str'
    }

    attribute_map = {
        'key': 'key',
        'title': 'title',
        'count': 'count',
        'records': 'records',
        'image_url100': 'imageUrl100',
        'image_url250': 'imageUrl250',
        'image_url500': 'imageUrl500'
    }

    def __init__(self, key=None, title=None, count=None, records=None, image_url100=None, image_url250=None, image_url500=None):  # noqa: E501
        """SaveTVWebApiResponseModelsRecordGroup - a model defined in Swagger"""  # noqa: E501

        self._key = None
        self._title = None
        self._count = None
        self._records = None
        self._image_url100 = None
        self._image_url250 = None
        self._image_url500 = None
        self.discriminator = None

        if key is not None:
            self.key = key
        if title is not None:
            self.title = title
        if count is not None:
            self.count = count
        if records is not None:
            self.records = records
        if image_url100 is not None:
            self.image_url100 = image_url100
        if image_url250 is not None:
            self.image_url250 = image_url250
        if image_url500 is not None:
            self.image_url500 = image_url500

    @property
    def key(self):
        """Gets the key of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501


        :return: The key of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this SaveTVWebApiResponseModelsRecordGroup.


        :param key: The key of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def title(self):
        """Gets the title of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501


        :return: The title of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this SaveTVWebApiResponseModelsRecordGroup.


        :param title: The title of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def count(self):
        """Gets the count of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501


        :return: The count of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this SaveTVWebApiResponseModelsRecordGroup.


        :param count: The count of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def records(self):
        """Gets the records of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501


        :return: The records of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501
        :rtype: list[SaveTVWebApiResponseModelsRecord]
        """
        return self._records

    @records.setter
    def records(self, records):
        """Sets the records of this SaveTVWebApiResponseModelsRecordGroup.


        :param records: The records of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501
        :type: list[SaveTVWebApiResponseModelsRecord]
        """

        self._records = records

    @property
    def image_url100(self):
        """Gets the image_url100 of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501


        :return: The image_url100 of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501
        :rtype: str
        """
        return self._image_url100

    @image_url100.setter
    def image_url100(self, image_url100):
        """Sets the image_url100 of this SaveTVWebApiResponseModelsRecordGroup.


        :param image_url100: The image_url100 of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501
        :type: str
        """

        self._image_url100 = image_url100

    @property
    def image_url250(self):
        """Gets the image_url250 of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501


        :return: The image_url250 of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501
        :rtype: str
        """
        return self._image_url250

    @image_url250.setter
    def image_url250(self, image_url250):
        """Sets the image_url250 of this SaveTVWebApiResponseModelsRecordGroup.


        :param image_url250: The image_url250 of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501
        :type: str
        """

        self._image_url250 = image_url250

    @property
    def image_url500(self):
        """Gets the image_url500 of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501


        :return: The image_url500 of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501
        :rtype: str
        """
        return self._image_url500

    @image_url500.setter
    def image_url500(self, image_url500):
        """Sets the image_url500 of this SaveTVWebApiResponseModelsRecordGroup.


        :param image_url500: The image_url500 of this SaveTVWebApiResponseModelsRecordGroup.  # noqa: E501
        :type: str
        """

        self._image_url500 = image_url500

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SaveTVWebApiResponseModelsRecordGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SaveTVWebApiResponseModelsRecordGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
