# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SaveTVWebApiResponseModelsRecordOperation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'telecast_id': 'int',
        'success': 'bool',
        'errors': 'list[OlympWebApiResponseModelsError]'
    }

    attribute_map = {
        'telecast_id': 'telecastId',
        'success': 'success',
        'errors': 'errors'
    }

    def __init__(self, telecast_id=None, success=None, errors=None):  # noqa: E501
        """SaveTVWebApiResponseModelsRecordOperation - a model defined in Swagger"""  # noqa: E501

        self._telecast_id = None
        self._success = None
        self._errors = None
        self.discriminator = None

        if telecast_id is not None:
            self.telecast_id = telecast_id
        if success is not None:
            self.success = success
        if errors is not None:
            self.errors = errors

    @property
    def telecast_id(self):
        """Gets the telecast_id of this SaveTVWebApiResponseModelsRecordOperation.  # noqa: E501


        :return: The telecast_id of this SaveTVWebApiResponseModelsRecordOperation.  # noqa: E501
        :rtype: int
        """
        return self._telecast_id

    @telecast_id.setter
    def telecast_id(self, telecast_id):
        """Sets the telecast_id of this SaveTVWebApiResponseModelsRecordOperation.


        :param telecast_id: The telecast_id of this SaveTVWebApiResponseModelsRecordOperation.  # noqa: E501
        :type: int
        """

        self._telecast_id = telecast_id

    @property
    def success(self):
        """Gets the success of this SaveTVWebApiResponseModelsRecordOperation.  # noqa: E501


        :return: The success of this SaveTVWebApiResponseModelsRecordOperation.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this SaveTVWebApiResponseModelsRecordOperation.


        :param success: The success of this SaveTVWebApiResponseModelsRecordOperation.  # noqa: E501
        :type: bool
        """

        self._success = success

    @property
    def errors(self):
        """Gets the errors of this SaveTVWebApiResponseModelsRecordOperation.  # noqa: E501


        :return: The errors of this SaveTVWebApiResponseModelsRecordOperation.  # noqa: E501
        :rtype: list[OlympWebApiResponseModelsError]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this SaveTVWebApiResponseModelsRecordOperation.


        :param errors: The errors of this SaveTVWebApiResponseModelsRecordOperation.  # noqa: E501
        :type: list[OlympWebApiResponseModelsError]
        """

        self._errors = errors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SaveTVWebApiResponseModelsRecordOperation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SaveTVWebApiResponseModelsRecordOperation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
