# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SaveTVWebApiRequestModelsFullTextSearchChannel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'search_query': 'str',
        'name': 'str'
    }

    attribute_map = {
        'search_query': 'searchQuery',
        'name': 'name'
    }

    def __init__(self, search_query=None, name=None):  # noqa: E501
        """SaveTVWebApiRequestModelsFullTextSearchChannel - a model defined in Swagger"""  # noqa: E501

        self._search_query = None
        self._name = None
        self.discriminator = None

        if search_query is not None:
            self.search_query = search_query
        if name is not None:
            self.name = name

    @property
    def search_query(self):
        """Gets the search_query of this SaveTVWebApiRequestModelsFullTextSearchChannel.  # noqa: E501


        :return: The search_query of this SaveTVWebApiRequestModelsFullTextSearchChannel.  # noqa: E501
        :rtype: str
        """
        return self._search_query

    @search_query.setter
    def search_query(self, search_query):
        """Sets the search_query of this SaveTVWebApiRequestModelsFullTextSearchChannel.


        :param search_query: The search_query of this SaveTVWebApiRequestModelsFullTextSearchChannel.  # noqa: E501
        :type: str
        """

        self._search_query = search_query

    @property
    def name(self):
        """Gets the name of this SaveTVWebApiRequestModelsFullTextSearchChannel.  # noqa: E501


        :return: The name of this SaveTVWebApiRequestModelsFullTextSearchChannel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SaveTVWebApiRequestModelsFullTextSearchChannel.


        :param name: The name of this SaveTVWebApiRequestModelsFullTextSearchChannel.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SaveTVWebApiRequestModelsFullTextSearchChannel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SaveTVWebApiRequestModelsFullTextSearchChannel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
