# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SaveTVWebApiRequestModelsTvStationFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_recordable': 'bool',
        'has_live_stream': 'bool',
        'sort': 'list[OlympCollectionsSortDescription]',
        'fields': 'list[str]'
    }

    attribute_map = {
        'is_recordable': 'isRecordable',
        'has_live_stream': 'hasLiveStream',
        'sort': 'sort',
        'fields': 'fields'
    }

    def __init__(self, is_recordable=None, has_live_stream=None, sort=None, fields=None):  # noqa: E501
        """SaveTVWebApiRequestModelsTvStationFilter - a model defined in Swagger"""  # noqa: E501

        self._is_recordable = None
        self._has_live_stream = None
        self._sort = None
        self._fields = None
        self.discriminator = None

        if is_recordable is not None:
            self.is_recordable = is_recordable
        if has_live_stream is not None:
            self.has_live_stream = has_live_stream
        if sort is not None:
            self.sort = sort
        if fields is not None:
            self.fields = fields

    @property
    def is_recordable(self):
        """Gets the is_recordable of this SaveTVWebApiRequestModelsTvStationFilter.  # noqa: E501


        :return: The is_recordable of this SaveTVWebApiRequestModelsTvStationFilter.  # noqa: E501
        :rtype: bool
        """
        return self._is_recordable

    @is_recordable.setter
    def is_recordable(self, is_recordable):
        """Sets the is_recordable of this SaveTVWebApiRequestModelsTvStationFilter.


        :param is_recordable: The is_recordable of this SaveTVWebApiRequestModelsTvStationFilter.  # noqa: E501
        :type: bool
        """

        self._is_recordable = is_recordable

    @property
    def has_live_stream(self):
        """Gets the has_live_stream of this SaveTVWebApiRequestModelsTvStationFilter.  # noqa: E501


        :return: The has_live_stream of this SaveTVWebApiRequestModelsTvStationFilter.  # noqa: E501
        :rtype: bool
        """
        return self._has_live_stream

    @has_live_stream.setter
    def has_live_stream(self, has_live_stream):
        """Sets the has_live_stream of this SaveTVWebApiRequestModelsTvStationFilter.


        :param has_live_stream: The has_live_stream of this SaveTVWebApiRequestModelsTvStationFilter.  # noqa: E501
        :type: bool
        """

        self._has_live_stream = has_live_stream

    @property
    def sort(self):
        """Gets the sort of this SaveTVWebApiRequestModelsTvStationFilter.  # noqa: E501


        :return: The sort of this SaveTVWebApiRequestModelsTvStationFilter.  # noqa: E501
        :rtype: list[OlympCollectionsSortDescription]
        """
        return self._sort

    @sort.setter
    def sort(self, sort):
        """Sets the sort of this SaveTVWebApiRequestModelsTvStationFilter.


        :param sort: The sort of this SaveTVWebApiRequestModelsTvStationFilter.  # noqa: E501
        :type: list[OlympCollectionsSortDescription]
        """

        self._sort = sort

    @property
    def fields(self):
        """Gets the fields of this SaveTVWebApiRequestModelsTvStationFilter.  # noqa: E501


        :return: The fields of this SaveTVWebApiRequestModelsTvStationFilter.  # noqa: E501
        :rtype: list[str]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this SaveTVWebApiRequestModelsTvStationFilter.


        :param fields: The fields of this SaveTVWebApiRequestModelsTvStationFilter.  # noqa: E501
        :type: list[str]
        """

        self._fields = fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SaveTVWebApiRequestModelsTvStationFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SaveTVWebApiRequestModelsTvStationFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
