# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SaveTVWebApiResponseModelsUser(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'full_name': 'str',
        'contract': 'SaveTVWebApiResponseModelsContract',
        'record_buffer': 'SaveTVWebApiResponseModelsRecordBuffer',
        'record_format': 'SaveTVWebApiResponseModelsRecordFormat',
        'guard': 'SaveTVWebApiResponseModelsGuard',
        'catch_all': 'SaveTVWebApiResponseModelsCatchAll',
        'retention_time': 'SaveTVWebApiResponseModelsRetentionTime',
        'playlists': 'SaveTVWebApiResponseModelsPlaylistAccountState',
        'live_streaming': 'SaveTVWebApiResponseModelsLiveStreaming',
        'erotic': 'SaveTVWebApiResponseModelsErotic'
    }

    attribute_map = {
        'id': 'id',
        'full_name': 'fullName',
        'contract': 'contract',
        'record_buffer': 'recordBuffer',
        'record_format': 'recordFormat',
        'guard': 'guard',
        'catch_all': 'catchAll',
        'retention_time': 'retentionTime',
        'playlists': 'playlists',
        'live_streaming': 'liveStreaming',
        'erotic': 'erotic'
    }

    def __init__(self, id=None, full_name=None, contract=None, record_buffer=None, record_format=None, guard=None, catch_all=None, retention_time=None, playlists=None, live_streaming=None, erotic=None):  # noqa: E501
        """SaveTVWebApiResponseModelsUser - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._full_name = None
        self._contract = None
        self._record_buffer = None
        self._record_format = None
        self._guard = None
        self._catch_all = None
        self._retention_time = None
        self._playlists = None
        self._live_streaming = None
        self._erotic = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if full_name is not None:
            self.full_name = full_name
        if contract is not None:
            self.contract = contract
        if record_buffer is not None:
            self.record_buffer = record_buffer
        if record_format is not None:
            self.record_format = record_format
        if guard is not None:
            self.guard = guard
        if catch_all is not None:
            self.catch_all = catch_all
        if retention_time is not None:
            self.retention_time = retention_time
        if playlists is not None:
            self.playlists = playlists
        if live_streaming is not None:
            self.live_streaming = live_streaming
        if erotic is not None:
            self.erotic = erotic

    @property
    def id(self):
        """Gets the id of this SaveTVWebApiResponseModelsUser.  # noqa: E501


        :return: The id of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SaveTVWebApiResponseModelsUser.


        :param id: The id of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def full_name(self):
        """Gets the full_name of this SaveTVWebApiResponseModelsUser.  # noqa: E501


        :return: The full_name of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this SaveTVWebApiResponseModelsUser.


        :param full_name: The full_name of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :type: str
        """

        self._full_name = full_name

    @property
    def contract(self):
        """Gets the contract of this SaveTVWebApiResponseModelsUser.  # noqa: E501


        :return: The contract of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :rtype: SaveTVWebApiResponseModelsContract
        """
        return self._contract

    @contract.setter
    def contract(self, contract):
        """Sets the contract of this SaveTVWebApiResponseModelsUser.


        :param contract: The contract of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :type: SaveTVWebApiResponseModelsContract
        """

        self._contract = contract

    @property
    def record_buffer(self):
        """Gets the record_buffer of this SaveTVWebApiResponseModelsUser.  # noqa: E501


        :return: The record_buffer of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :rtype: SaveTVWebApiResponseModelsRecordBuffer
        """
        return self._record_buffer

    @record_buffer.setter
    def record_buffer(self, record_buffer):
        """Sets the record_buffer of this SaveTVWebApiResponseModelsUser.


        :param record_buffer: The record_buffer of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :type: SaveTVWebApiResponseModelsRecordBuffer
        """

        self._record_buffer = record_buffer

    @property
    def record_format(self):
        """Gets the record_format of this SaveTVWebApiResponseModelsUser.  # noqa: E501


        :return: The record_format of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :rtype: SaveTVWebApiResponseModelsRecordFormat
        """
        return self._record_format

    @record_format.setter
    def record_format(self, record_format):
        """Sets the record_format of this SaveTVWebApiResponseModelsUser.


        :param record_format: The record_format of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :type: SaveTVWebApiResponseModelsRecordFormat
        """

        self._record_format = record_format

    @property
    def guard(self):
        """Gets the guard of this SaveTVWebApiResponseModelsUser.  # noqa: E501


        :return: The guard of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :rtype: SaveTVWebApiResponseModelsGuard
        """
        return self._guard

    @guard.setter
    def guard(self, guard):
        """Sets the guard of this SaveTVWebApiResponseModelsUser.


        :param guard: The guard of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :type: SaveTVWebApiResponseModelsGuard
        """

        self._guard = guard

    @property
    def catch_all(self):
        """Gets the catch_all of this SaveTVWebApiResponseModelsUser.  # noqa: E501


        :return: The catch_all of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :rtype: SaveTVWebApiResponseModelsCatchAll
        """
        return self._catch_all

    @catch_all.setter
    def catch_all(self, catch_all):
        """Sets the catch_all of this SaveTVWebApiResponseModelsUser.


        :param catch_all: The catch_all of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :type: SaveTVWebApiResponseModelsCatchAll
        """

        self._catch_all = catch_all

    @property
    def retention_time(self):
        """Gets the retention_time of this SaveTVWebApiResponseModelsUser.  # noqa: E501


        :return: The retention_time of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :rtype: SaveTVWebApiResponseModelsRetentionTime
        """
        return self._retention_time

    @retention_time.setter
    def retention_time(self, retention_time):
        """Sets the retention_time of this SaveTVWebApiResponseModelsUser.


        :param retention_time: The retention_time of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :type: SaveTVWebApiResponseModelsRetentionTime
        """

        self._retention_time = retention_time

    @property
    def playlists(self):
        """Gets the playlists of this SaveTVWebApiResponseModelsUser.  # noqa: E501


        :return: The playlists of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :rtype: SaveTVWebApiResponseModelsPlaylistAccountState
        """
        return self._playlists

    @playlists.setter
    def playlists(self, playlists):
        """Sets the playlists of this SaveTVWebApiResponseModelsUser.


        :param playlists: The playlists of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :type: SaveTVWebApiResponseModelsPlaylistAccountState
        """

        self._playlists = playlists

    @property
    def live_streaming(self):
        """Gets the live_streaming of this SaveTVWebApiResponseModelsUser.  # noqa: E501


        :return: The live_streaming of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :rtype: SaveTVWebApiResponseModelsLiveStreaming
        """
        return self._live_streaming

    @live_streaming.setter
    def live_streaming(self, live_streaming):
        """Sets the live_streaming of this SaveTVWebApiResponseModelsUser.


        :param live_streaming: The live_streaming of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :type: SaveTVWebApiResponseModelsLiveStreaming
        """

        self._live_streaming = live_streaming

    @property
    def erotic(self):
        """Gets the erotic of this SaveTVWebApiResponseModelsUser.  # noqa: E501


        :return: The erotic of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :rtype: SaveTVWebApiResponseModelsErotic
        """
        return self._erotic

    @erotic.setter
    def erotic(self, erotic):
        """Sets the erotic of this SaveTVWebApiResponseModelsUser.


        :param erotic: The erotic of this SaveTVWebApiResponseModelsUser.  # noqa: E501
        :type: SaveTVWebApiResponseModelsErotic
        """

        self._erotic = erotic

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SaveTVWebApiResponseModelsUser, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SaveTVWebApiResponseModelsUser):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
