# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SaveTVWebApiRequestModelsStarFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ids': 'list[int]',
        'is_highlight': 'bool',
        'has_birthday_today': 'bool',
        'plays_part_in_upcoming_telecast': 'bool',
        'limit': 'int',
        'offset': 'int',
        'no_paging_header': 'bool',
        'q': 'str',
        'sort': 'list[OlympCollectionsSortDescription]',
        'fields': 'list[str]'
    }

    attribute_map = {
        'ids': 'ids',
        'is_highlight': 'isHighlight',
        'has_birthday_today': 'hasBirthdayToday',
        'plays_part_in_upcoming_telecast': 'playsPartInUpcomingTelecast',
        'limit': 'limit',
        'offset': 'offset',
        'no_paging_header': 'noPagingHeader',
        'q': 'q',
        'sort': 'sort',
        'fields': 'fields'
    }

    def __init__(self, ids=None, is_highlight=None, has_birthday_today=None, plays_part_in_upcoming_telecast=None, limit=None, offset=None, no_paging_header=None, q=None, sort=None, fields=None):  # noqa: E501
        """SaveTVWebApiRequestModelsStarFilter - a model defined in Swagger"""  # noqa: E501

        self._ids = None
        self._is_highlight = None
        self._has_birthday_today = None
        self._plays_part_in_upcoming_telecast = None
        self._limit = None
        self._offset = None
        self._no_paging_header = None
        self._q = None
        self._sort = None
        self._fields = None
        self.discriminator = None

        if ids is not None:
            self.ids = ids
        if is_highlight is not None:
            self.is_highlight = is_highlight
        if has_birthday_today is not None:
            self.has_birthday_today = has_birthday_today
        if plays_part_in_upcoming_telecast is not None:
            self.plays_part_in_upcoming_telecast = plays_part_in_upcoming_telecast
        if limit is not None:
            self.limit = limit
        if offset is not None:
            self.offset = offset
        if no_paging_header is not None:
            self.no_paging_header = no_paging_header
        if q is not None:
            self.q = q
        if sort is not None:
            self.sort = sort
        if fields is not None:
            self.fields = fields

    @property
    def ids(self):
        """Gets the ids of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501


        :return: The ids of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :rtype: list[int]
        """
        return self._ids

    @ids.setter
    def ids(self, ids):
        """Sets the ids of this SaveTVWebApiRequestModelsStarFilter.


        :param ids: The ids of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :type: list[int]
        """

        self._ids = ids

    @property
    def is_highlight(self):
        """Gets the is_highlight of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501


        :return: The is_highlight of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :rtype: bool
        """
        return self._is_highlight

    @is_highlight.setter
    def is_highlight(self, is_highlight):
        """Sets the is_highlight of this SaveTVWebApiRequestModelsStarFilter.


        :param is_highlight: The is_highlight of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :type: bool
        """

        self._is_highlight = is_highlight

    @property
    def has_birthday_today(self):
        """Gets the has_birthday_today of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501


        :return: The has_birthday_today of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :rtype: bool
        """
        return self._has_birthday_today

    @has_birthday_today.setter
    def has_birthday_today(self, has_birthday_today):
        """Sets the has_birthday_today of this SaveTVWebApiRequestModelsStarFilter.


        :param has_birthday_today: The has_birthday_today of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :type: bool
        """

        self._has_birthday_today = has_birthday_today

    @property
    def plays_part_in_upcoming_telecast(self):
        """Gets the plays_part_in_upcoming_telecast of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501


        :return: The plays_part_in_upcoming_telecast of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :rtype: bool
        """
        return self._plays_part_in_upcoming_telecast

    @plays_part_in_upcoming_telecast.setter
    def plays_part_in_upcoming_telecast(self, plays_part_in_upcoming_telecast):
        """Sets the plays_part_in_upcoming_telecast of this SaveTVWebApiRequestModelsStarFilter.


        :param plays_part_in_upcoming_telecast: The plays_part_in_upcoming_telecast of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :type: bool
        """

        self._plays_part_in_upcoming_telecast = plays_part_in_upcoming_telecast

    @property
    def limit(self):
        """Gets the limit of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501


        :return: The limit of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this SaveTVWebApiRequestModelsStarFilter.


        :param limit: The limit of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :type: int
        """

        self._limit = limit

    @property
    def offset(self):
        """Gets the offset of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501


        :return: The offset of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this SaveTVWebApiRequestModelsStarFilter.


        :param offset: The offset of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :type: int
        """

        self._offset = offset

    @property
    def no_paging_header(self):
        """Gets the no_paging_header of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501


        :return: The no_paging_header of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :rtype: bool
        """
        return self._no_paging_header

    @no_paging_header.setter
    def no_paging_header(self, no_paging_header):
        """Sets the no_paging_header of this SaveTVWebApiRequestModelsStarFilter.


        :param no_paging_header: The no_paging_header of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :type: bool
        """

        self._no_paging_header = no_paging_header

    @property
    def q(self):
        """Gets the q of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501


        :return: The q of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :rtype: str
        """
        return self._q

    @q.setter
    def q(self, q):
        """Sets the q of this SaveTVWebApiRequestModelsStarFilter.


        :param q: The q of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :type: str
        """

        self._q = q

    @property
    def sort(self):
        """Gets the sort of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501


        :return: The sort of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :rtype: list[OlympCollectionsSortDescription]
        """
        return self._sort

    @sort.setter
    def sort(self, sort):
        """Sets the sort of this SaveTVWebApiRequestModelsStarFilter.


        :param sort: The sort of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :type: list[OlympCollectionsSortDescription]
        """

        self._sort = sort

    @property
    def fields(self):
        """Gets the fields of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501


        :return: The fields of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :rtype: list[str]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this SaveTVWebApiRequestModelsStarFilter.


        :param fields: The fields of this SaveTVWebApiRequestModelsStarFilter.  # noqa: E501
        :type: list[str]
        """

        self._fields = fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SaveTVWebApiRequestModelsStarFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SaveTVWebApiRequestModelsStarFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
