# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SaveTVWebApiResponseModelsTvStationGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'tv_stations': 'list[SaveTVWebApiResponseModelsTvStation]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'tv_stations': 'tvStations'
    }

    def __init__(self, id=None, name=None, tv_stations=None):  # noqa: E501
        """SaveTVWebApiResponseModelsTvStationGroup - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._tv_stations = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if tv_stations is not None:
            self.tv_stations = tv_stations

    @property
    def id(self):
        """Gets the id of this SaveTVWebApiResponseModelsTvStationGroup.  # noqa: E501


        :return: The id of this SaveTVWebApiResponseModelsTvStationGroup.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SaveTVWebApiResponseModelsTvStationGroup.


        :param id: The id of this SaveTVWebApiResponseModelsTvStationGroup.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this SaveTVWebApiResponseModelsTvStationGroup.  # noqa: E501


        :return: The name of this SaveTVWebApiResponseModelsTvStationGroup.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SaveTVWebApiResponseModelsTvStationGroup.


        :param name: The name of this SaveTVWebApiResponseModelsTvStationGroup.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def tv_stations(self):
        """Gets the tv_stations of this SaveTVWebApiResponseModelsTvStationGroup.  # noqa: E501


        :return: The tv_stations of this SaveTVWebApiResponseModelsTvStationGroup.  # noqa: E501
        :rtype: list[SaveTVWebApiResponseModelsTvStation]
        """
        return self._tv_stations

    @tv_stations.setter
    def tv_stations(self, tv_stations):
        """Sets the tv_stations of this SaveTVWebApiResponseModelsTvStationGroup.


        :param tv_stations: The tv_stations of this SaveTVWebApiResponseModelsTvStationGroup.  # noqa: E501
        :type: list[SaveTVWebApiResponseModelsTvStation]
        """

        self._tv_stations = tv_stations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SaveTVWebApiResponseModelsTvStationGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SaveTVWebApiResponseModelsTvStationGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
