from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from swagger_client.api.channel_time_frames__get_api import ChannelTimeFramesGetApi
from swagger_client.api.channels__delete_api import ChannelsDeleteApi
from swagger_client.api.channels__get_api import ChannelsGetApi
from swagger_client.api.channels__post_api import ChannelsPostApi
from swagger_client.api.credentials__post_api import CredentialsPostApi
from swagger_client.api.erotic_videos__get_api import EroticVideosGetApi
from swagger_client.api.folx_tv_videos__get_api import FolxTvVideosGetApi
from swagger_client.api.internet_service_providers__get_api import InternetServiceProvidersGetApi
from swagger_client.api.playlist_types__get_api import PlaylistTypesGetApi
from swagger_client.api.playlists__delete_api import PlaylistsDeleteApi
from swagger_client.api.playlists__get_api import PlaylistsGetApi
from swagger_client.api.playlists__post_api import PlaylistsPostApi
from swagger_client.api.record_formats__get_api import RecordFormatsGetApi
from swagger_client.api.record_states__get_api import RecordStatesGetApi
from swagger_client.api.records__delete_api import RecordsDeleteApi
from swagger_client.api.records__get_api import RecordsGetApi
from swagger_client.api.records__post_api import RecordsPostApi
from swagger_client.api.stars__delete_api import StarsDeleteApi
from swagger_client.api.stars__get_api import StarsGetApi
from swagger_client.api.stars__post_api import StarsPostApi
from swagger_client.api.telecasts__get_api import TelecastsGetApi
from swagger_client.api.telecasts__post_api import TelecastsPostApi
from swagger_client.api.time_blocks__get_api import TimeBlocksGetApi
from swagger_client.api.tv_categories__get_api import TvCategoriesGetApi
from swagger_client.api.tv_station_groups__get_api import TvStationGroupsGetApi
from swagger_client.api.tv_stations__get_api import TvStationsGetApi
from swagger_client.api.user__get_api import UserGetApi
from swagger_client.api.user__post_api import UserPostApi
from swagger_client.api.version__get_api import VersionGetApi
