# coding: utf-8

"""
    Save.TV API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class PlaylistsDeleteApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def playlists_delete(self, **kwargs):  # noqa: E501
        """Deletes the playlists specified by the identifiers.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_delete(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[int] playlistids: A comma separated list of playlist identifiers.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_delete_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.playlists_delete_with_http_info(**kwargs)  # noqa: E501
            return data

    def playlists_delete_with_http_info(self, **kwargs):  # noqa: E501
        """Deletes the playlists specified by the identifiers.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_delete_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[int] playlistids: A comma separated list of playlist identifiers.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['playlistids']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_delete" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'playlistids' in params:
            query_params.append(('playlistids', params['playlistids']))  # noqa: E501
            collection_formats['playlistids'] = 'multi'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/v3/playlists', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def playlists_delete_0(self, id, **kwargs):  # noqa: E501
        """Deletes the playlist specified by the identifier.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_delete_0(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: The playlist identifier. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_delete_0_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.playlists_delete_0_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def playlists_delete_0_with_http_info(self, id, **kwargs):  # noqa: E501
        """Deletes the playlist specified by the identifier.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_delete_0_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: The playlist identifier. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_delete_0" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `playlists_delete_0`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/v3/playlists/{id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def playlists_follow_delete(self, id, **kwargs):  # noqa: E501
        """Remove the playlist from the saved (followed) playlists.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_follow_delete(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: The playlist identifier. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_follow_delete_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.playlists_follow_delete_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def playlists_follow_delete_with_http_info(self, id, **kwargs):  # noqa: E501
        """Remove the playlist from the saved (followed) playlists.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_follow_delete_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: The playlist identifier. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_follow_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `playlists_follow_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/v3/playlists/{id}/follow', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def playlists_follow_delete_0(self, **kwargs):  # noqa: E501
        """Removes the playlists from the saved (followed) playlists.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_follow_delete_0(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[int] playlistids: A comma separated list of playlist identifiers.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_follow_delete_0_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.playlists_follow_delete_0_with_http_info(**kwargs)  # noqa: E501
            return data

    def playlists_follow_delete_0_with_http_info(self, **kwargs):  # noqa: E501
        """Removes the playlists from the saved (followed) playlists.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_follow_delete_0_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[int] playlistids: A comma separated list of playlist identifiers.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['playlistids']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_follow_delete_0" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'playlistids' in params:
            query_params.append(('playlistids', params['playlistids']))  # noqa: E501
            collection_formats['playlistids'] = 'multi'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/v3/playlists/follow', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def playlists_items_delete_item(self, id, telecast_id, **kwargs):  # noqa: E501
        """Deletes the given telecast from the playlist.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_items_delete_item(id, telecast_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: The playlist identifier. (required)
        :param int telecast_id: The telecast identifier. (required)
        :return: SaveTVWebApiResponseModelsPlaylistItemOperation
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_items_delete_item_with_http_info(id, telecast_id, **kwargs)  # noqa: E501
        else:
            (data) = self.playlists_items_delete_item_with_http_info(id, telecast_id, **kwargs)  # noqa: E501
            return data

    def playlists_items_delete_item_with_http_info(self, id, telecast_id, **kwargs):  # noqa: E501
        """Deletes the given telecast from the playlist.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_items_delete_item_with_http_info(id, telecast_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: The playlist identifier. (required)
        :param int telecast_id: The telecast identifier. (required)
        :return: SaveTVWebApiResponseModelsPlaylistItemOperation
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'telecast_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_items_delete_item" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `playlists_items_delete_item`")  # noqa: E501
        # verify the required parameter 'telecast_id' is set
        if ('telecast_id' not in params or
                params['telecast_id'] is None):
            raise ValueError("Missing the required parameter `telecast_id` when calling `playlists_items_delete_item`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501
        if 'telecast_id' in params:
            path_params['telecastId'] = params['telecast_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/v3/playlists/{id}/items/{telecastid}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SaveTVWebApiResponseModelsPlaylistItemOperation',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def playlists_items_delete_items(self, id, **kwargs):  # noqa: E501
        """Deletes the given telecasts from the playlist.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_items_delete_items(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: The playlist identifier. (required)
        :param list[int] telecastids: A comma separated list of telecast identifiers.
        :return: list[SaveTVWebApiResponseModelsPlaylistItemOperation]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.playlists_items_delete_items_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.playlists_items_delete_items_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def playlists_items_delete_items_with_http_info(self, id, **kwargs):  # noqa: E501
        """Deletes the given telecasts from the playlist.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.playlists_items_delete_items_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: The playlist identifier. (required)
        :param list[int] telecastids: A comma separated list of telecast identifiers.
        :return: list[SaveTVWebApiResponseModelsPlaylistItemOperation]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'telecastids']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method playlists_items_delete_items" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `playlists_items_delete_items`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'telecastids' in params:
            query_params.append(('telecastids', params['telecastids']))  # noqa: E501
            collection_formats['telecastids'] = 'multi'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/v3/playlists/{id}/items', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[SaveTVWebApiResponseModelsPlaylistItemOperation]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
